[build.nixpacksPlan]
providers = ["node"]

[build.nixpacksPlan.phases.setup]
cmds = ["npm install -g pnpm"]

[build.nixpacksPlan.phases.install]
cmds = ["cd apps/backend && pnpm install"]

[build]
builder = "nixpacks"
buildCommand = "cd apps/backend && pnpm run build"

[deploy]
startCommand = "cd apps/backend && pnpm run deploy && pnpm start"

