[build]
builder = "nixpacks"
buildCommand = "cd apps/backend && pnpm install && pnpm run build"

[deploy]
startCommand = "cd apps/backend && pnpm run deploy && pnpm start"

[build.nixpacksPlan]
providers = ["node"]

[phases.setup]
cmds = ["npm install -g pnpm"]

[phases.install]
cmds = ["pnpm i"]
